### ISSUE TITLE
Sistema de Interpretação

### ISSUE THREAD

**Issue by pittersnider** [BlackHubOS/EventoZero#10]
O sistema de interpretação é um sistema que permite que o jogador configure coisas, de uma forma MUITO mais fácil.

A ideia da API é a seguinte, conforme planejado

``` java
Interpreter mode = new Interpreter("nome qualquer");
Question question = mode.question("&cO evento deverá ter pvp?", Patterns.BOOLEAN.yes(outra_question).no(outra_question));
```

Para fazer o jogador entrar no modo

``` java
mode.join(player);
```

Quando o jogador está no modo 'joined', ele fica invisível para os demais jogadores, não pode tomar dano.

Os seguintes eventos devem ser tratados:
- AsyncPlayerChatEvent - pegar o que ele digitar
- PlayerCommandPreprocessEvent - útil para caso esteja em uma question sobre bloquear comanods
- PlayerQuitEvent - se ele der logout, desregistrar ele do mode
- PlayerKickEvent - se ele for kickado, desregistrar ele do mode

**Comment by leonardosnt** [comment]
ce8fc2bc8e1416c78e5a0f78d7bb09d1195b510f & 04b93aa1da27baa35d26320091ead5d122fce87a
