### ISSUE TITLE
Lista de comandos a criar

### ISSUE THREAD

**Issue by leonardosnt** [BlackHubOS/EventoZero#11]
Lista de comandos a criar
- [x] ez iniciar <evento> = Iniciar um evento manualmente
- [x] ez cancelar <evento> = Cancela um evento ocorrendo
- [x] ez add entrada <evento> = Adiciona uma nova entrada
- [ ] ez del entrada <evento> <id> = Remove uma entrada
- [ ] ez entradas <evento> = Obtém as entradas e suas IDs
- [ ] ez camarote <evento> = Adiciona um novo camarote
- [ ] ez pvp <evento> <allow\deny> = Define o status de pvp
- [ ] ez mc <evento> <allow\deny> = Bloqueia ou permite MC
- [ ] ez tools = Abre a caixa de ferramentas do eventozero
- [ ] ez cmd -b <evento> <comando> = Bloquear um comando
- [ ] ez cmd -r <evento> <comando> = Remover um comando bloqueado
- [ ] ez cmd -c <evento> = Limpar comandos bloqueados
- [ ] ez cmd -l <evento> = Ver a lista de comandos bloqueados
- [ ] ez potion -b <evento> <id> = Bloquear uma poção no evento
- [ ] ez potion -r <evento> <id> = Remover uma poção bloqueada
- [ ] ez potion -c <evento> = Limpar pots bloqueados
- [ ] ez potion -l <evento> = Ver lista de pots bloqueadas
- [ ] ez potion -ids = Obter os IDs das poções do jogo
- [ ] ez kit -p <evento> <nome> = Permitir que um kit possa ser usado
- [ ] ez kit -b <evento> <nome> = Bloquear que um kit possa ser usado
- [ ] ez kit -l <evento> = Visualizar kits permitidos e bloqueados
- [ ] ez kit -c <evento> = Limpar dados de kits do evento
- [ ] ez kit -r <nome> = Remover um kit do plugin (apaga totalmente)
- [ ] ez kit price <valor> = Modifica o preço de um kit
- [ ] ez kit armor <valor> = Define a armadura do kit como a que você está usando
- [ ] ez kit contents <valor> = Define os itens do kit como os que você tem no inventário
- [ ] ez party -e <evento> = Ativa as partys no evento
- [ ] ez party -d <evento> = Desativa partys no evento
- [ ] ez party -l <evento> <quantia> = Define a quantia máxima de jogadores por party
- [ ] ez max <evento> <quantia> = Define o número máximo de jogadores (autoinicia)
- [ ] ez min <evento> <quantia> = Define o número mínimo de jogadores para poder iniciar o evento
- [ ] ez autostop <evento> <tempo> = Define o tempo para terminar o evento se não houver ganhadores.
- [ ] ez setengine <evento> <arquivo.sc> = Definir uma engine para um evento
- [ ] ez placements <evento> <quantia> = Define o limite de colocações
- [ ] ez points add <player> <quantia> = Creditar pontos à um jogador
- [ ] ez points rem <player> <quantia> = Debitar pontos de um jogador
- [ ] ez points set <player> <quantia> = Modificar pontos de um jogador
- [ ] ez points coins <quantia> = Define quanto 01 ponto vale em coins
- [ ] ez updates = Apenas verifica se há novos updats
- [ ] ez upgrade = Verifica e aplica o update automaticamente se existir
- [ ] ez reload = Faz reload completo no plugin
- [ ] ez disable = Desativa o plugin completamente

**Comment by HugoSilvaF** [comment]
Interessante

**Comment by jhrldev** [comment]
Vai ser demorado kkk

**Comment by leonardosnt** [comment]
Como ficaria(+ -) usando meu sisteminha e.e

```java
package io.github.leonardosnt.testy;

import io.github.bktlib.command.*;
import io.github.bktlib.command.args.CommandArgs;

@Command(
        name = "ez",
        usageTarget = UsageTarget.BOTH, // que bosta de nome eim? kkk
        usage = "...",
        subCommands = { // ou " this::* " ou " this::[cmd,potion,kit,party,potions] "
                "this::cmd",
                "this::potion",
                "this::kit",
                "this::party",
                "this::points",
        },
        description = "..."
)
public class EZCommands extends CommandBase
{
    @Override
    public CommandResult onExecute(CommandSource src, CommandArgs args)
    {
        // execute os sub comandos menores ex iniciar, cancelar
        return CommandResult.success();
    }

    @SubCommand( name = "cmd"  )
    CommandResult cmd( CommandSource src, CommandArgs args )
    {
        /*
             ez cmd -b <evento> <comando> = Bloquear um comando
             ez cmd -r <evento> <comando> = Remover um comando bloqueado
             ez cmd -c <evento> = Limpar comandos bloqueados
             ez cmd -l <evento> = Ver a lista de comandos bloqueados
         */
        return CommandResult.success();
    }

    @SubCommand( name = "potion"  )
    CommandResult potion( CommandSource src, CommandArgs args )
    {
        /*
             ez potion -b <evento> <id> = Bloquear uma poção no evento
             ez potion -r <evento> <id> = Remover uma poção bloqueada
             ez potion -c <evento> = Limpar pots bloqueados
             ez potion -l <evento> = Ver lista de pots bloqueadas
             ez potion -ids = Obter os IDs das poções do jogo
         */
        return CommandResult.success();
    }

    @SubCommand( name = "kit"  )
    CommandResult kit( CommandSource src, CommandArgs args )
    {
       /*
             ez kit -p <evento> <nome> = Permitir que um kit possa ser usado
             ez kit -b <evento> <nome> = Bloquear que um kit possa ser usado
             ez kit -l <evento> = Visualizar kits permitidos e bloqueados
             ez kit -c <evento> = Limpar dados de kits do evento
             ez kit -r <nome> = Remover um kit do plugin (apaga totalmente)
             ez kit price <valor> = Modifica o preço de um kit
             ez kit armor <valor> = Define a armadura do kit como a que você está usando
             ez kit contents <valor> = Define os itens do kit como os que você tem no inventário
        */
        return CommandResult.success();
    }

    @SubCommand( name = "party"  )
    CommandResult party( CommandSource src, CommandArgs args )
    {
        /*
             ez party -e <evento> = Ativa as partys no evento
             ez party -d <evento> = Desativa partys no evento
             ez party -l <evento> <quantia> = Define a quantia máxima de jogadores por party
         */
        return CommandResult.success();
    }

    @SubCommand( name = "points"  )
    CommandResult points( CommandSource src, CommandArgs args )
    {
        /*
             ez points add <player> <quantia> = Creditar pontos à um jogador
             ez points rem <player> <quantia> = Debitar pontos de um jogador
             ez points set <player> <quantia> = Modificar pontos de um jogador
             ez points coins <quantia> = Define quanto 01 ponto vale em coins
         */
        return CommandResult.success();
    }
}
```

**Comment by leonardosnt** [comment]
86b458a1d1259efdaa64369d5344e6e7749f6ec6
