### ISSUE TITLE
Definir padrão

### ISSUE THREAD

**Issue by leonardosnt** [BlackHubOS/EventoZero#14]
Temos que definir um padrão de identação, pra melhorar a legibilidade do código, pois cada um coloca de um jeito...

Ex

```
if (){
}
```

```
if ()
{
}
```

**Comment by jhrldev** [comment]
Eu somente sigo o Google Java Style, que é:

``` java
if (CONDIÇÃO) {

}
```

**Comment by pittersnider** [comment]
{
}

**Comment by leonardosnt** [comment]
{
}

**Comment by leonardosnt** [comment]
Temos que votar ou sei la huehue

**Comment by HugoSilvaF** [comment]
eu uso 

if(){

}

**Comment by leonardosnt** [comment]
Eu concordo em usar 

``` java
for (;;) {

}
```

**Comment by HugoSilvaF** [comment]
Se for para ser votado, Google Java Style veceria.

**Comment by leonardosnt** [comment]
Na real é que ficou empate 2 a 2, mas pra mim qualquer um ta bom.

**Comment by HugoSilvaF** [comment]
na verdade 3 x 1

CrazyDev
JonathanxD
leonardosnt 

``` Java
if (CONDIÇÃO) {

}
```

ReedFlake

``` Java
if (CONDIÇÃO) 
{

}
```

**Comment by leonardosnt** [comment]
Não filho, eu uso a mesma do Atom, já faz tempo, mas pra mim tanto faz.

**Comment by HugoSilvaF** [comment]
Se pra tu tanto faz, vamos usar 

``` Java
if (CONDIÇÃO) {

}
```

**Comment by leonardosnt** [comment]
Eu já to usando, só falta ver com o atom, ai nós "reformatamos" tudo.
