### ISSUE TITLE
ItemFactory não funcionando ?

### ISSUE THREAD

**Issue by leonardosnt** [BlackHubOS/EventoZero#15]
```
ItemFactory f = new ItemFactory(
        "item(317)",
        null
);

ItemStack is = f.getPreparedItem(); // é null
```

Por algum motivo ele ta parando aqui https://github.com/BlackHubOS/EventoZero/blob/master/src/br/com/blackhubos/eventozero/factory/ItemFactory.java#L238

**Comment by pittersnider** [comment]
item{id:data}   ----------> { }
Vou trocar para (), o que você acha?

**Comment by pittersnider** [comment]
É, na documentação estava (), culpa minha, vou trocar agora.

**Comment by leonardosnt** [comment]
Eu achei mas massa com (), mas se q sabe, eu nem olhei, eu peguei direto de um arquivo que tinha la pra testar.
