### ISSUE TITLE
Gerenciador de dependencias

### ISSUE THREAD

**Issue by leonardosnt** [BlackHubOS/EventoZero#4]
Colocar um "gerenciador de dependencias", tipo maven, gradle, não é bem essa "tradução" mas ...., ou colocar sla, uma pasta com as dependências, por que senão, quem quiser contribuir vai ter que ficar procurando.

**Comment by jhrldev** [comment]
Vamos analisar :dancer:

**Comment by jhrldev** [comment]
Aceito! Estarei implementando desde já!
