### ISSUE TITLE
Erro de mysql

### ISSUE THREAD

**Issue by pittersnider** [BlackHubOS/EventoZero#8]
Foi realizado testes com mysql (pelo Eclipse RUN) na classe StorageProvider, e houve um erro: "SQLException: No suitable driver for"

O projeto continha o mysql-connector-bin.jar e o driver foi registrado (DriverManager.register())

**Comment by HugoSilvaF** [comment]
Tente realizar os testes do mysql fora do eclipse, execute o plug-in
